### ISSUE TITLE
Context Switch not picking the first non-null value

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#10]
Or better, I probably didn't understand well enough how it should work. 

I have the following situation, where 4 input images have to arrive to an upscaler. They come from 4 different functions of the workflow. 

At any given, only one of the 4 inputs is really carrying an image. 

I can't solve this problem with ordinary switches as, I'm told, ComfyUI will not work if inputs are empty. So, I thought your Context Switch would work as "automatically choose the first non-null context to continue onward with". 

Hence the configuration:

<img width="895" alt="Screenshot 2023-09-02 at 10 33 55" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/5a7e79f0-bbb0-4700-b5a4-b9fbcfdc5a8f">

Now, let's say that the only non-null image in my case is input 2, which carries the Refiner image. I'd expect that to be selected and passed to the Context Switch. Instead, I receive this error:

```
Traceback (most recent call last):
  File "/Users/xyz/Desktop/AI/Tools/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/Desktop/AI/Tools/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/Desktop/AI/Tools/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/Desktop/AI/Tools/ComfyUI/comfy_extras/nodes_upscale_model.py", line 39, in upscale
    in_img = image.movedim(-1,-3).to(device)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'movedim'
```

I also attach the whole workflow for more context:

![Context Switch Test](https://github.com/rgthree/rgthree-comfy/assets/9775949/1649bcbe-8181-463c-93a3-cebcc1afa194)

**Comment by rgthree** [comment]
Thanks for the whole workflow, that is very helpful (and love it, very organized!)

I think this is a fair feature request and probably beneficial. Let me see if I can make this work for you.

With that said, it is currently working as its meant to, and we can get your workflow to work as well.

The Context and Context Switch nodes were built was to utilize muting for the _Context_ node input. As of right now the Context node will always return a valid Context object, so, if you want it skipped you're meant to mute that input Context.

Your flow could work for the way these were built now by having your muter mute these Context nodes going into the Switch instead of the processing nodes. For the top two contexts (ReVision & Refiner), you can just mute the Context _instead of_ the KSampler and, since that "disconnects" the KSampler from the output node after the Switch, the KSamplers won't run just the same as if you muted the KSamplers themselves.

Same holds true for the Detailers, but it's a bit more complex because you have Preview nodes connected directly to the Detailer nodes "mask" outputs, which means they would still run for those outputs even if their later Context node was muted. What you would want to is to mute BOTH the Detailers like your doing to stop those directly-connected Preview nodes, AND also mute the corresponding Context node going into the Switch.

You can do this now with the new "Mute Repeater Node" which works essentially bundles a bunch of nodes for the Muter and shows just one toggle for all of them. (So, Muter Node is connected to the Repeater Node and shows one toggle for it, and both the Detailer AND its corresponding Context Switch are connected to the Repeater).

All to say, though, I think adding a feature to the Context Switch to see if a Context wraps all null values and skipping it is a nice one to have. I'll take a look.

**Comment by rgthree** [comment]
Alright, if you pull a fresh version now, your workflow should just work without any changes!

**Comment by UserWithLootsProblems** [comment]
I have a similar problem where: 'NoneType' object has no attribute 'movedim'. I am new to this so I don't understand what is the problem. Here is the error when I run stable diffusion: 
![image](https://github.com/rgthree/rgthree-comfy/assets/143909187/ae1d2298-2290-4a51-84a2-91bec07defc3)
Here is the error when I run stable diffusion: 
Here is the error when I run stable diffusion: 
![image](https://github.com/rgthree/rgthree-comfy/assets/143909187/13c74bd4-06fd-45d8-b39b-358e25ba5d68)
Error occurred when executing ImageScale:

'NoneType' object has no attribute 'movedim'

File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1416, in upscale
samples = image.movedim(-1,1)

**Comment by Unstable-Reality** [comment]
> Alright, if you pull a fresh version now, your workflow should just work without any changes!

It works perfectly, thank you!

**Comment by alessandroperilli** [comment]
> Alright, if you pull a fresh version now, your workflow should just work without any changes!

It works perfectly, thank you!
