### ISSUE TITLE
[Bug] Context Big ckpt_name appears to be a _list_, not a single string

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#120]
In Context Big, the ckpt_name attribute appears to be a _list_ of all checkpoints, when I expected this to be a string/text.

**Comment by ghostsquad** [comment]
How do I pass in the chkpt name to that context?

**Comment by rgthree** [comment]
There would be another node that has a model selector like the built-in model loader, but instead of loading a model, it outputs the model name as the model list type (to be connected to a model loader that changed the widget selector to an input).

I don't remember the custom node that did that; it'd really be fore ppl that want to output the checkpoint name, like to a custom SAVE METADATA node
