### ISSUE TITLE
how to use Any Switch

### ISSUE THREAD

**Issue by NNNenov** [rgthree/rgthree-comfy#123]
Apologies if this is already documented somewhere, but I couldn't find it, and the node doesnt seem to be listed in the readme.
I see it has multiple inputs, but how is decided/dictated which input to "switch" to / use?
![image](https://github.com/rgthree/rgthree-comfy/assets/9900819/5cc1d990-fe4f-492a-a64b-f00b30af2ee3)

**Comment by rgthree** [comment]
Ah, yea.. it's a derivation of the Context Switch, but let's you add anything instead of just contexts. It works by automatically passing the through the first (and ideally the only) non-null/empty input; so in your screenshot, if you intend to use `any_02` you would likely mute the connected node going to `any_01` essentially making it null.

The README explains why this is much more advantageous than other node switches, as when you mute the path leading to `any_01` here, it won't do the work. Other switches with a number to manually set 1 or 2 don't stop the work being done leading up to it; that can only be achieved through muting.

**Comment by NNNenov** [comment]
ahh I see! so if any_01 and any_02 were muted, but I had active inputs in any_03 and any_04, the output would be any_03 since that's the first / next available active input? 
This is nice, in my case I wanted to be able to pick the selection using an integer, but its good to know about this option.

**Comment by rgthree** [comment]
Exactly, a lot of rgthree-comfy nodes are built around muting/bypassing, which is turning “off” portions of the workflow and having the rest respond correctly, all to make executions as fast as possible.
