### ISSUE TITLE
Overlapping Groups in Fast Groups Bypasser

### ISSUE THREAD

**Issue by ricperry** [rgthree/rgthree-comfy#141]
Behavior is indeterminant. If ANY of the overlapping groups is in bypass, the node should be bypassed. This will help simplify layouts and sectioning. For example, if I have 2 separate detailer workflows, one in latent space, one in pixel space, I want to be able to bypass the FaceDetailer and/or the HandDetailer. I might also want to bypass either the latent space or the pixel space workflow. So I might have the following 4 sets of nodes, LF, LH,PF, PH, arranged as follows:
     [F]  [H]
[L]   1   2
[P]   3  4

If I want to just use the LatentSpace detailer workflow and just do hands, I'd bypass FaceDetailer and PixelSpace Upscaler. So I would bypass Pixel and Face. But currently, depending on the order I do enable the bypass, I might get a bypassed pixel space workflow, but the hand detailer in the pixel space workflow isn't bypassed, so it throws an exception.

**Comment by rgthree** [comment]
The Groups Muter/Bypasser have binary switches for displays with two states: “off” meaning _all_ of the nodes are either muted or bypassed, and “on” meaning _any_ of the nodes are enabled. (Note that second state is _any_ not _all_ due to workflows that may change things out from under the group).

Activating the switch will change _all_ nodes in the group to the state; enabled when “on” and muted/bypassed when “off”.

The operation is deterministic, but keep in mind the state of the switches described above. For your workflow, the order of switching matters: you would need four groups as you laid out, “L” “P” “F” and “H”. Assuming you wanted LH enabled and others bypassed then, starting with all node enabled, you would simply bypass the “P” Group and then the “F” Group. In this case, only the “LH” portion should remain enabled (though “L” Group would show as “on” because _some_ of its nodes are enabled).

**Comment by ricperry** [comment]
Thanks for the reply. Love your work... one of my favorite custom nodes.
