### ISSUE TITLE
Feature request "reverse position" in the "position" option of the fast muter/bypasser property panel.

### ISSUE THREAD

**Issue by stephantual** [rgthree/rgthree-comfy#151]
I understand this is a minute thing, but it would be nice to have a 'reverse' position in addition to position for the sort order of the fast muter/bypasser property panel. While I understand that comfy thinks 'right to left', most people read 'left to right', so if have :

- Group A
- Group B
- Group C

.. having them listed as 'C, B, A' in the fast muter panel is hella confusing :) 

Thank for you considering this. Maybe there's a way through the custom alphabet option but i haven't figured it out :)

**Comment by rgthree** [comment]
It should be an intuitive order, you can choose to order them (from top to bottom) alphabetically or by position (“reading position”, like a book from top left and moving horizontally then down a line, etc).

Alphabetically, “Group A” should be before “Group B” which is before “Group C”. Obviously, I assume these aren’t the names, but you can customize the alphabet it sorts against, if you want to provide your actual names and order I could better provide an example.

**Comment by stephantual** [comment]
Of course. 
Here's the worfklow: https://comfyworkflows.com/workflows/eba55917-3c47-43ac-90d9-50a6441ef437 - it has a preview, saves you having to load it ;) 

You can see the 3 noise injectors are listed in the reverse order than they were expected (although correct by Comfy standards)

**Comment by rgthree** [comment]
Cool, thanks. So you have two options that will get you the sort you desire:

1. Keep the properties as-is (and therefore sort as `position`) but line the groups up more tightly; try to get the tops to all fall along the same horizontal line. I think I give about 30 pixels of leeway... so because the Img2Noise group is so much higher, it has a higher precendence. (If you think of it like reading a book, left-to-right, line-by-line, the Img2Noise group is on the "line" before the other two, so it's first by position).

2. Or, don't worry about position, open the properties and set the sort to `custom alphabet` and the custom alphabet here can just be `g,p,i` which will sort the toggles as you have the groups left to right ("g" for "Generate Noise...", "p" for "Power Noise", and "i" for "Img2Noise).
    - _(Custom alphabet can be more complex too. Let's say you had a group called "Img2Static" that you wanted first, your custom alphabet could be `img2s,g,p,i`)_

**Comment by stephantual** [comment]
Fantastic - the slight drop was the easiest option! Thanks a ton!
