### ISSUE TITLE
title reroutes node

### ISSUE THREAD

**Issue by Trobinou** [rgthree/rgthree-comfy#16]
Your 'reroute' node is great, but would it be possible to display the title?

**Comment by rgthree** [comment]
There was good reason for no labels at the time (specifically because labels don't show in the multi-directions the node allows), but with a bit more work we can probably add them... and Done.

There's now a "Show/Hide Title Label" menu item on right click (grouped with the connection layout, static sizes, etc) that will show the node's title (if not default) or the output connection type when there's one. (Also added some resizing options to the menu).

![titles](https://github.com/rgthree/rgthree-comfy/assets/476360/73bca108-80a6-447c-abab-a545541e1476)

Unfortunately, this is only on the dev branch for now at https://github.com/rgthree/rgthree-comfy/tree/dev which has a ton more features coming but requires some optimization in comfyui itself. Once https://github.com/comfyanonymous/ComfyUI/issues/1502 is fixed and/or https://github.com/comfyanonymous/ComfyUI/issues/1502 is merged, then this can land in rgthree/rgthree-comfy main.

**Comment by Trobinou** [comment]
Thank you so much, that's great news! 👍
