### ISSUE TITLE
add enhancement reroute

### ISSUE THREAD

**Issue by pvp-by** [rgthree/rgthree-comfy#17]
add the possibility to use resizing like in standard ComfyUI, by placing the cursor to the bottom right corner of the node and resize it by dragging and dropping.
and in your implementation there are no additional menus :
![image](https://github.com/rgthree/rgthree-comfy/assets/10133995/d3fb248c-cae7-4d86-a509-a388a3aa6608)
as well as a severe size limitation :
![image](https://github.com/rgthree/rgthree-comfy/assets/10133995/5e66300f-2eed-4393-9527-fc7a73820e15)

Thank you so much for your custom nodes

**Comment by rgthree** [comment]
There was good reason for no labels and no resizing at the time (specifically because labels don't show in the multi-directions the node allows), but with a bit more work we can probably add them... and Done.

There's now both a "Allow/No Resizing" menu item, and a "Show/Hide Title Label" menu item on right click (grouped with the connection layout, static sizes, etc).

Unfortunately, this is only on the `dev` branch for now at  https://github.com/rgthree/rgthree-comfy/tree/dev which has a ton more features coming but requires some optimization in comfyui itself. Once https://github.com/comfyanonymous/ComfyUI/issues/1502 is fixed and/or https://github.com/comfyanonymous/ComfyUI/issues/1502 is merged, then this can land in rgthree/rgthree-comfy main.

**Comment by pvp-by** [comment]
if it is relevant, I would like to ask for 1 more point that I may not have emphasized as a good practice.

in a normal `reroute` you can separately enable `show title` and separately enable the `show type` label . your version is already almost perfect both in terms of functionality and end-user friendliness.

Maybe this part (`show type` automatically indicates the type of the connected line instead of title) is missing for full delight. 

huge sps for your hard work, the major dev20 update is excellent.
