### ISSUE TITLE
[Feature Request] one button to .....

### ISSUE THREAD

**Issue by K-O-N-B** [rgthree/rgthree-comfy#171]
![image](https://github.com/rgthree/rgthree-comfy/assets/152141077/f36073f0-4184-4467-a152-2dc97f4070f6)
one button to switch all to buttons to yes and no.

**Comment by ghostsquad** [comment]
this could be useful to solve #175

**Comment by K-O-N-B** [comment]
hello, you mean like this? I am not sure I understand your answer.....

![image](https://github.com/rgthree/rgthree-comfy/assets/152141077/082b6c06-814d-481c-94b0-ed19e88f9501)

**Comment by ghostsquad** [comment]
I found that if you first "collect" the nodes (using the Collector), then the output from the collector to a Fast Muter/Bypasser, and also to a Repeater. Connect the repeater to the same fast muter/bypasser, you can make a quick "all/none" toggle. Though I still think this functionality should be baked into the node.

![image](https://github.com/rgthree/rgthree-comfy/assets/903488/13c6c961-95e5-4336-bb9f-7b5c3a7235b3)

**Comment by rgthree** [comment]
I do agree a toggle on the node itself could be useful and, in fact, I think there's a lot here I'm interested in making much more robust. But, until I get around to that, there is the "Fast Actions Button" that can be used right now to accomplish _almost_ completely what's needed.

![Screenshot 2024-03-28 211721](https://github.com/rgthree/rgthree-comfy/assets/476360/d00e01e6-e8af-4d58-9136-640057228370)

You can connect it to the muter/bypasser and have a one-button click to Mute/Bypass All, Enable All, or Toggle All. I say _almost_ because you may need two Fast Actions Button node to achieve exactly what's expected (One to mute/bypass, one to enable). "Toggle" will work, but it toggle's each widget independently, so if one was "on" and the rest "off" then "Toggle" will switch it to that one as "off" and the rest as "on".

You can also define a shortcut key for the Actions Button too.
