### ISSUE TITLE
Seed (rgthree) reverting to Fixed after several queued tasks

### ISSUE THREAD

**Issue by ricperry** [rgthree/rgthree-comfy#185]
I haven't figured out what's causing it, but only a couple of days ago, Seed (rgthree) started behaving unpredictably where after a few queued workflows, it reverts to the last random and refuses to stick on Randomize Each Time.

**Comment by rgthree** [comment]
Can you sync rgthree-comfy to the latest and try again? I just made some improvements that I think addressed some changes from last week that could have potentially broken the seed node. Thx!

**Comment by Edwinsiddy1** [comment]
I can confirm that this issue still happens on the most recent version

**Comment by ricperry** [comment]
Seems to work now for me.

**Comment by rgthree** [comment]
The last change from yesterday was a bit better and it wouldn't get stuck, but I could find cases where "-1" was sent as the seed, or the seed node showed a seed that was newer-but-not-sent to the server than the last seed.

The problem was that the seed node was built to intercept when ComfyUI generates the graph, change the widget value to a random seed, then let ComfyUI do it's normal thing, and then change back to "-1". However, other extensions (namely cg-use-everywhere) calls that graph generation very often and there were times that it would do it in between the setting of the widget and the server responding, causing funky behavior.

The latest [a1263d0](https://github.com/rgthree/rgthree-comfy/commit/a1263d0a7ce2f9ebaf4a4d3b984480bc70e49327) should fix all that as the seed node no longer touches the actual widget, and just intercepts the raw data being sent to the ComfyUI backend to set a random seed.
