### ISSUE TITLE
Seed node doesn't behave as expected in API

### ISSUE THREAD

**Issue by kklemon** [rgthree/rgthree-comfy#188]
I was surprised to see that the seed node behaves differently than in the frontend when used with the API. The given seed is just passed on instead of being randomized each time when the node is configured for random seed generation.

Upon closer inspection, it turns out that this is actually according to the underlying Python implementation. The actual logic for setting the seed according to the node configuration happens in the frontend implementation of the node which is not executed by the backend. 

I find this behavior a bit misleading and was thinking about possible solutions. One could be to make the Python implementation follow the expected intuitive behavior, i.e. pass on a random seed for "seed" = -1 and the fixed seed otherwise and intercept this behavior in the frontend code. Another possibility could be to highlight this behavior explicitly and provide a second node that behaves in the advertised way specifically for use with the API.

In any case, thanks for this great package, which surely has saved many users a lot of time.

**Comment by rgthree** [comment]
I'm not sure it's specifically "advertised" in a particular way or is misleading as the seed node works like ComfyUI's seed behavior already, just makes it much more intuitive. In that a built-in KSampler node with a `randomize` seed widget is also generated only in the frontend and, if using the API only, it would also not change the seed on the server even if set to "randomize."

There's a lot of reasons this is done on frontend rather than the backend, but there's also nothing stopping it from working on the server, even if discouraged. I added some code for just that case, with a bunch of warning logs, though, since it shouldn't be happening for users using ComfyUI's frontend "normally."
