### ISSUE TITLE
SDXL Power Prompt loads the same LORA twice

### ISSUE THREAD

**Issue by TheBill2001** [rgthree/rgthree-comfy#189]
Hi. I don't know if this is an intended behavior, but I noticed the SDXL Power Prompt loads the same LORA twice if the LORA string is in both `prompt_g` and `prompt_l`.

For context, I followed this [post on Reddit](https://www.reddit.com/r/StableDiffusion/comments/15ggn9w/sdxl_mini_study_clip_g_vs_clip_l_best_prompting/) about using full prompt for both, rather than separate. To make my life easier, I use a separate string node as my prompt and plug it in both of the power prompt input. This works fine, but if I put in a LORA string then the node will load the LORA twice.

My current workaround is having two separate string nodes: `Positive` and `LORA`. The output of `Positive` + a comma +  `LORA` goes to `prompt_g`. Only the output of `Positive` goes to `prompt_l`.

![Screenshot_20240406_235848](https://github.com/rgthree/rgthree-comfy/assets/68230358/51d74568-b40f-4012-bf98-e71d4b517a0a)

Don't know if this matter?

**Comment by rgthree** [comment]
Ah, correct. Power Prompt just parses the text as-is. This is by design and I think I'd rather not bake in too much magic. Your text cancatenation would be the right solution here to keep the `<lora:...>` text.

However, I did just push a change with a new node, `Power Lora Loader` which allows you to more succinctly add, toggle, and manipulate lora strengths. I think I prefer it more than the `<lora:...>` tags at the moment. Give it a try and let me know what you think.
