### ISSUE TITLE
reroute node error

### ISSUE THREAD

**Issue by idesign2018** [rgthree/rgthree-comfy#202]
![image](https://github.com/rgthree/rgthree-comfy/assets/42263070/492b2245-3e56-4180-84da-1b93c2bc5745)
Installed rgthree-comfy, but for the reroute node, it still shows an error, not sure what's causing it

**Comment by DrJKL** [comment]
Do you see any errors in either of the consoles?
https://www.coursera.support/s/article/learner-000001653-How-to-open-the-Javascript-console?language=en_US

**Comment by 52Hz-p** [comment]
我也遇到了这个问题，是因为翻译插件的问题，冲突了

**Comment by 52Hz-p** [comment]
@Regis Gaughan, III不知道后续是否会解决这个问题，跟界面翻译的那个插件中文有冲突，快捷键也有冲突了

**Comment by idesign2018** [comment]
> 您在两个控制台中看到任何错误吗？ https://www.coursera.support/s/article/learner-000001653-How-to-open-the-Javascript-console?language=en_US

yes
![image](https://github.com/rgthree/rgthree-comfy/assets/42263070/5681bfb1-ae11-4cc6-91fd-c85e085cb3c6)

**Comment by idesign2018** [comment]
> 我也遇到了这个问题，是因为翻译插件的问题，冲突了

还真是，我切换到英文状态就没有出现错误，希望可以得到修复

**Comment by idesign2018** [comment]
> Do you see any errors in either of the consoles? https://www.coursera.support/s/article/learner-000001653-How-to-open-the-Javascript-console?language=en_US

This error is caused by a conflict with the [AIGODLIKE-ComfyUI-Translation](https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION) plugin.

**Comment by 52Hz-p** [comment]
> > 我也遇到了这个问题，是因为翻译插件的问题，冲突了
> 
> 还真是，我切换到中文状态就没有出现错误，希望可以得到修复

有个办法解决就是随时备份一个低版本的，然后去翻译里把之前rgh的jos复制到新的里面就好了

**Comment by rgthree** [comment]
Looks like there was a conflict in AIGODLIKE-COMFYUI-TRANSLATION. I was able to fix this from rgthree-comfy with d8ea2cb90fa5107b70b0e0dd7dd7d37c42a4f68a and cleanup a bunch too. However, there are some improvements the AIGODLIKE-COMFYUI-TRANSLATION extension could make.

Recently, rgthree-comfy made a change (db062961ed4a3cd92f4eb2b8eeedbcc742b5d5e9) which allows other so other extensions' `onNodeCreated` would run on all of the rgthree-comfy nodes. This is generally beneficial for the extensions ecosystem, though puts rgthree-comfy at risk as now other extensions can hack stuff a bit.

It looks like the AIGODLIKE-COMFYUI-TRANSLATION is automatically setting nodes' titles and input/output slots to translated strings; which makes sense to translate. However, when it does so, it also overwrites any custom title/labels the user may have specifically given to the node/slot. Specifically, it looks like rgthree-comfy reroute nodes now show the a slot label because this extension is setting that field.

This didn't matter before because AIGODLIKE-COMFYUI-TRANSLATION never got the chance to modify reroute, and now it does after db062961ed4a3cd92f4eb2b8eeedbcc742b5d5e9. I'll file an issue there.

**Comment by 52Hz-p** [comment]
> 看起来 AIGODLIKE-COMFYUI-TRANSLATION 中存在冲突。我能够使用[d8ea2cb](https://github.com/rgthree/rgthree-comfy/commit/d8ea2cb90fa5107b70b0e0dd7dd7d37c42a4f68a)从 rg Three-comfy 修复此问题并清理一堆。但是，AIGODLIKE-COMFYUI-TRANSLATION 扩展可以做出一些改进。
> 
> 最近，rg Three-comfy 进行了更改（[db06296](https://github.com/rgthree/rgthree-comfy/commit/db062961ed4a3cd92f4eb2b8eeedbcc742b5d5e9)），允许其他扩展`onNodeCreated`在所有 rg Three-comfy 节点上运行。这通常对扩展生态系统有利，但也使 rg Three-comfy 面临风险，因为现在其他扩展可能会破解一些东西。
> 
> 看起来 AIGODLIKE-COMFYUI-TRANSLATION 会自动将节点的标题和输入/输出槽设置为翻译后的字符串；这翻译起来很有意义。然而，当它这样做时，它还会覆盖用户可能专门赋予节点/槽的任何自定义标题/标签。具体来说，看起来 rg Three-comfy 重新路由节点现在显示插槽标签，因为此扩展正在设置该字段。
> 
> 以前这并不重要，因为 AIGODLIKE-COMFYUI-TRANSLATION 从未有机会修改重新路由，现在在[db06296](https://github.com/rgthree/rgthree-comfy/commit/db062961ed4a3cd92f4eb2b8eeedbcc742b5d5e9)之后就可以了。我将在那里提出问题。

是的，所以我只能暂时通过将以前版本里的AIGODLIKE-COMFYUI-TRANSLATION 中的rg翻译文件更改为旧版本，也可以解决问题，只是没有了翻译，不过并不影响使用。

**Comment by idesign2018** [comment]
> 看起来 AIGODLIKE-COMFYUI-TRANSLATION 中存在冲突。我能够使用[d8ea2cb](https://github.com/rgthree/rgthree-comfy/commit/d8ea2cb90fa5107b70b0e0dd7dd7d37c42a4f68a)从 rg Three-comfy 修复此问题并清理一堆。但是，AIGODLIKE-COMFYUI-TRANSLATION 扩展可以做出一些改进。
> 
> 最近，rg Three-comfy 进行了更改（[db06296](https://github.com/rgthree/rgthree-comfy/commit/db062961ed4a3cd92f4eb2b8eeedbcc742b5d5e9)），允许其他扩展`onNodeCreated`在所有 rg Three-comfy 节点上运行。这通常对扩展生态系统有利，但也使 rg Three-comfy 面临风险，因为现在其他扩展可能会破解一些东西。
> 
> 看起来 AIGODLIKE-COMFYUI-TRANSLATION 会自动将节点的标题和输入/输出槽设置为翻译后的字符串；这翻译起来很有意义。然而，当它这样做时，它还会覆盖用户可能专门赋予节点/槽的任何自定义标题/标签。具体来说，看起来 rg Three-comfy 重新路由节点现在显示插槽标签，因为此扩展正在设置该字段。
> 
> 以前这并不重要，因为 AIGODLIKE-COMFYUI-TRANSLATION 从未有机会修改重新路由，现在在[db06296](https://github.com/rgthree/rgthree-comfy/commit/db062961ed4a3cd92f4eb2b8eeedbcc742b5d5e9)之后就可以了。我将在那里提出问题。

Great job, have the bugs been fixed?
