### ISSUE TITLE
Workflow Link Fixer doesn't save the fixed workflow

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#21]
This explains why so many people on Reddit told me that whenever they load my workflow the find a bunch of nodes disconnected, and why on random reloads, I experience the same with two nodes:

<img width="890" alt="Screenshot 2023-09-16 at 20 29 42" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/6923ea0c-59dd-47de-a428-2fcc35746dee">

However, I cannot fix. When I click the fix and save button, nothing happens. Tried on Vivaldi and Safari. No ad blockers.

**Comment by rgthree** [comment]
Yea! I was actually going to reach out to you. I just pushe da change that I believe fixes this for you. I've also added a "Fix in place" link to that popup that should attempt the same fix in ComfyUI directly.

Let me know how if that fixes it for you.

Aside, all my newer workflows seem to be fine, so if this was caused by some of my older versions then hopefully they're fixed. But I may add a config option to monitor the links data in real time, and alert if something goes wonky. Since you're often iterating, I may reach out to see if you'd be willing to opt-into this. (basically, change config line, and then file an issue if comfyui alerts to something).

**Comment by Unstable-Reality** [comment]
@alessandroperilli Great, thank you. I'm already trying your new nodes and they are amazing. I'm modifying the workflow to incorporate the new Context Big and Context Switch Big, and of course, the labelled reroutes. I'll let you know. 

I have a couple of feat asks about some of the new nodes. I'm opening a new issue right now.

**Comment by alessandroperilli** [comment]
@rgthree  Great, thank you. I'm already trying your new nodes and they are amazing. I'm modifying the workflow to incorporate the new Context Big and Context Switch Big, and of course, the labelled reroutes. I'll let you know.

I have a couple of feat asks about some of the new nodes. I'm opening a new issue right now.

**Comment by alessandroperilli** [comment]
Fix in place works fine. I'll check how well it fixed the workflow in the next few hours.

Feel free to reach out to me in private to test the config option to monitor data in real time. Happy to help.
