### ISSUE TITLE
Bookmark node - sticky keys

### ISSUE THREAD

**Issue by jtc-jtc** [rgthree/rgthree-comfy#238]
Sorry to open this up again. I have noticed that bookmark nodes now seem to get a sort of unintended sticky keys function when using modifier key combinations in comfyui. For example if I use `cmd + c` and `cmd + v` to copy and past a node, the bookmark nodes think that the C & V keys are still being pressed after they are released. Hopefully this video explains better. It seems to happen when using any combination of keys, similar function is seen when using cmd + enter to queue. 

https://github.com/rgthree/rgthree-comfy/assets/30127464/4e67a87f-156e-4bed-ae99-392f85f5fd1d

_Originally posted by @joetcurrie in https://github.com/rgthree/rgthree-comfy/issues/227#issuecomment-2134318746_

**Comment by rgthree** [comment]
Thanks for opening this up. Are you using Safari? Can you also try on Chromium and/or FireFox.

The details here are that the browser window must be losing focus and/or comfyui is swallowing the event such that rgthree-comfy never receives a signal the key has been lifted (unfortunately, browsers don’t have a check for ‘is this key currently down’ but need to track state through a manual ‘key is pressed’ and ‘key is released’; but if that second signal is never sent then the program would forever think the key is still pressed).

**Comment by JoeNavark** [comment]
If you alt-tab out and back and then set the bookmark does it work properly?

**Comment by rgthree** [comment]
I'm unable to reproduce on windows, so this must be something specific to Mac. I've added some debug code that could help me a bit and confirm what it is that could be sticking for you.

Pull the latest rgthree-comfy and open ComfyUI with the following hash: `http://127.0.0.1:8188/#rgthree-dev=true&rgthree-debug=true`. Now, you should see a live view of the current keys rgthree-comfy things are being pressed in the top-right of the screen.

Can you confirm when you copy something that the keys stick as shown in that debug box even after you release? (As JoeNavark mentioned, if you leave the tab and come back, it should clear any down keys too).
- If you copy a node, is CMD and C stuck, or just C?
- What happens if you press CMD + C, but don't have any node to copy, etc?
- Are there other cases of CMD + ? that stick other than copy and paste.

It's not impossible that ComfyUI is intercepting and stopping the event so it can copy. It's not happening on windows, so if that's the case for Mac only then that would be wildly unfortunate...

**Comment by satche** [comment]
Since I'm also on OSX, I tested a bit for you.

Copying a node or text with CMD+C will only cause the C key to get stuck. In fact, all combinations with the CMD (Meta) key will cause the associated key to get stuck. For example, if I use CMD+Enter to queue a prompt, the Enter key will get stuck. It doesn't appear to do that with any other key (Ctrl, Alt, Fn, ...).

Unfocusing the window (like switching tabs in the browser) will immediately unstick the key. Also, pressing the stuck key will unstick it as well. For example, if C is stuck after a CMD+C, I just have to press C to unstuck it.

**Comment by rgthree** [comment]
Interesting, I can see why CMD + C and CMD + V would stick. But I can't find a reason why CMD + Enter would, other than Mac just always not sending a keydown if CMD is pressed. Not impossible, I suppose.

I added a handler so if the META/COMMAND key is lifted (which is working), then rgthree-comfy will clear any other keys that may be stuck. Since I don't have a Mac, let me know how this works.

**Comment by satche** [comment]
It seems to work just fine! Thank you!
