### ISSUE TITLE
context big scheduler array broken after update

### ISSUE THREAD

**Issue by michaelLochlann** [rgthree/rgthree-comfy#249]
after updating a bunch of nodes in comyfui it looks like they added some new scheduler types so the Context Big, which i use everywhere, is broken since the arrays of scheduler types don't match.

it does work with the ksampler though which is weird.

FaceDetailerPipe 275:
  - Return type mismatch between linked nodes: scheduler, ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform'] != ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'AYS SDXL', 'AYS SD1', 'AYS SVD']

**Comment by rgthree** [comment]
This looks like it's something specific in the FaceDetailerPipe. Those 'AYS SDXL', 'AYS SD1', 'AYS SVD' values do not exist in the schedules according to ComfyUI (For instance, KSampler's schedulers do not have those).

But really, it's just a bad handling of combos from within Comfy UI's widget handling, which is where the error is coming from... I actually don't think there's anything I can fix here, since the list I'm getting is what Comfy says are the available schedulers.

**Comment by rgthree** [comment]
I remember how you can get around the restriction because ComfyUI doesn't check too hard when things get complex for it.

Place a reroute (either an rgthree reroute or a comfyui reroute) in between the two nodes. Connect the FaceDetailerPipe's scheduler input to the reroute's output first, then connect the ContextBig's scheduler output to the reroute input. ComfyUI should not stop this connection from what I've found.
