### ISSUE TITLE
[BUG?] Reroute node doesn't connect to KSampler when transporting Sampler and Scheduler values

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#251]
I had the following problem for months, but I never got around to opening this issue. Sorry. 
I'm not 100% sure the reroute node is to blame here. It might be the source node. Nonetheless:

<img width="1476" alt="Screenshot 2024-06-15 at 11 06 44" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/e3a8d895-cc1b-43f8-941a-ed57ee0b3845">

In the screenshot above, the `Context Big` node is carrying `Sampler` and `Scheduler` information coming from an [SD Parameter Generator](https://github.com/receyuki/comfyui-prompt-reader-node) node. 

Obviously, I don't want a straight connection between those two outputs (red box on the left) and the `KSampler` inputs (red box on the right). I want to pass through the `Reroute` nodes below (red oval at the bottom). But there's no way. 

No matter what I do, I can't connect those two. 

Now, this behavior has changed over time:

- I remember a time when I could do it without problems.
- Then, once the problem arose, I remember a more recent time where I could put a [pythongosssss](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) Reroute node in between your Reroute and the KSampler, or some other acrobatics, and it would work.

Now it works with nothing.

Given that the `SD Parameter Generator` node has not been modified in ages, I assume the problem is somewhere else. But maybe I'm wrong.

Thanks for looking into this!

**Comment by rgthree** [comment]
**Note: You can get around the check that ComfyUI makes by connecting the reroute's output to the KSampler first, then you can connect the the reroute input second.**

Yea, I think we found that bug a while ago in another bug thread, that ComfyUI broke it a few months ago, even for the built-in ComfyUI Reroute nodes too. We created https://github.com/comfyanonymous/ComfyUI/issues/2690

Unfortunately, I can't fix it just for rgthree-comfy reroutes because it's a core part of ComfyUI's widget handling that has this bug (and, it's the bug is actually coming from the KSampler checking, not the reroute anyway).

**Comment by alessandroperilli** [comment]
Thanks for the quick reply and the workaround. That's probably how I did it the first time without realizing it.

It's amusing that I'm twice associated with that 6-month open issue. With a queue of 1,500 open issues, I see very slim chances of this ever being fixed.
