### ISSUE TITLE
Feature suggestion: node output and input remember choice suggestions on dragging to nothing

### ISSUE THREAD

**Issue by diodiogod** [rgthree/rgthree-comfy#257]
Your Context node when dragged don't suggest another Context node.
Most of the time your reroute don't suggest another reroute.

I think you could maybe fix this for your nodes, but a great feature would be to make Comfy remember when we drag any connection to nothing and then "add" a node manually, make that chosen node to always show when the same connection get dragged by the same node. I think It would help so much with expanding workflows.

Thank you so much!
![image](https://github.com/rgthree/rgthree-comfy/assets/160325160/7048acb7-89fa-4972-a3c1-bb109a5e3b89)

**Comment by rgthree** [comment]
You're right. ComfyUI only compiles the suggestion nodes from "required" inputs, but the CONTEXT input/output are optional so ComfyUI skips them. Just commited a fix to manually add all the Context nodes to this suggestion box.

It looks like ComfyUI does add reroute (including rgthree reroute), so that seems to be working.
