### ISSUE TITLE
Workflow restore/load/import breaks after be08b0f

### ISSUE THREAD

**Issue by devocalypse** [rgthree/rgthree-comfy#265]
Getting the following error for any commits after be08b0f on my persistent workflow.
```
Loading aborted due to error reloading workflow data
TypeError: self.groupData.oldToNewWidgetMap[n] is undefined

GroupNodeHandler/this.node.onNodeCreated@http://127.0.0.1:8188/extensions/core/groupNode.js:922:26
createNode@http://127.0.0.1:8188/lib/litegraph.core.js:478:22
init/LiteGraph.createNode@http://127.0.0.1:8188/extensions/cg-use-everywhere/use_everywhere.js:260:35
LGraph.prototype.configure@http://127.0.0.1:8188/lib/litegraph.core.js:2215:38
#addConfigureHandler/LGraph.prototype.configure@http://127.0.0.1:8188/scripts/app.js:1416:22
init/LGraph.prototype.configure@http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29
init/LGraph.prototype.configure@http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:69:21
loadGraphData@http://127.0.0.1:8188/scripts/app.js:1900:15

This may be due to the following script:
/extensions/core/groupNode.js
```

Reverting back to be08b0f via 
**git reset be08b0f --hard** 
fixes it but any subsequent update will break it again.

I am using multiple impact workflow components using rgthree in their innards and having to unpack every one, then repack, then fix inputs and outputs is a major undertaking.
Is there any way convert the bugging old version data to new version data by editing the json instead?

**Comment by rgthree** [comment]
Hmmm.. I'm not sure why that change would cause an error here. Though, I'm not too surprised ComfyUI's groupNodes are where the error lies.

I don't really use the groupNodes in ComfyUI, but I just tried adding some with and without my nodes, but can't recreate this error.

Is it possible you could trim down your workflow into just a fews nodes that seem to cause the issue?

**Comment by devocalypse** [comment]
I apologize for it taking so long, I managed to trim the workflow down to a single component.

I've added packed and unpacked variants. The unpacked one loads with the newest rgthree - no problem.
The packed one however breaks and fails to even render the view properly and prevents all other nodes and components from loading.

[workflow-1component - packed and unpacked.zip](https://github.com/user-attachments/files/16040363/workflow-1component.-.packed.and.unpacked.zip)

**Comment by rgthree** [comment]
I honestly don't know how you're using the comfy Group Nodes. They have never seemed to work for me. Even just now trying to get just a simple seed value passed through with an otherwise clean workflow doesn't work. I don't want to recommend you not use them directly, but I don't trust them to work myself.

Anyway, I did find the issue of why its not loading, thanks for the example. ComfyUI's Group Node code doesn't like that your example workflow has a groupNode configuration that has the Any Switch inputs marked as hidden. This is likely due to a recent change so the Any Switch, Context Switch and Context Merge now have dynamic inputs allow you to add infinite number of inputs to switch against, rather than the hardcoded limit at five.

Unfortunately, I can't fix it forward from rgthree-comfy since the issue is directly in ComfyUI's group nodes. I'm sorry, but you'll have to edit the JSON directly to remove the configuration data for these inputs.

In the workflow JSON, under the group's `config` JS object, you'll see something like this (where "4" here is the link id the group node has for the Any Switch):
```
"4": {
  "input": {
    "any_03": {
      "visible": false
    },
    "any_04": {
      "visible": false
    },
    "any_05": {
      "visible": false
    }
  }
},
```
Since these are now dynamic, the groupNode code doesn't like that they're styled too. You'll want to remove the entire "input" data object.

---

**Alternatively, you could edit comfyui's code directly** to allow your workflows with this issue to load by opening `/comfyui/web/extensions/core/groupNode.js` and find the line that looks like this (for me, it's line 922):
```
const widgetName = self.groupData.oldToNewWidgetMap[n][w];
```
And add a `?.` in between the `[n]` and the `[w]` so it becomes:
```
const widgetName = self.groupData.oldToNewWidgetMap[n]?.[w];
```

_Note, if there's an update to this line in the future, you may need to undo this change before git lets you update it, as it would think there's a conflict._

**Comment by devocalypse** [comment]
Thank you very much for the exhaustive explanation, I really appreciate it.
I was using the group nodes to minimize the screen space and links that certain sections require, hide the unneeded fields and inputs and make an overall cleaner look compartmentalizing functionally separate zones. It also helps me reduce connection line clutter which is so bad in my case that when I un-hide the connection lines the whole thing slows to a crawl and I can't stand that.

After considering how technically limiting using these groups is, however, and taking into account the new n-number of any switches and in the name of future compatibility I guess I'll just un-group them and stash their inner workings beyond the workflows borders. This will break importing previously generated images but at least will guarantee that future ones will not break like that. I'll just keep a frozen copy of the version that still loads them and be done with that.

Once again, thanks for taking time to look into this and for making this essential node collection as well.
