### ISSUE TITLE
It's time to shrink ".git" directory.

### ISSUE THREAD

**Issue by O-O1024** [rgthree/rgthree-comfy#272]
![image](https://github.com/rgthree/rgthree-comfy/assets/44624598/05045250-517f-4c4f-8821-f84da05d8932)

170M/175M

**Comment by dotJack** [comment]
Probably some blobs from mp4s bouncing around as far as I could tell. 

I got my local dir down to 33mb by running `git gc --prune=now`.
I think `git fetch --unshallow` would reset this (also `reset --hard origin/main` or a new clone)

Not sure how to  set this up as a default though. I'm also quite surprised that manager doesn't just use shallow for all the custom nodes since they're not meant for active dev?
