### ISSUE TITLE
Feature Request: Fast Group Muter / Bypasser output an optional Int

### ISSUE THREAD

**Issue by gisu** [rgthree/rgthree-comfy#282]
In my workflow I use bypassers to control groups, as well as various switches (e.g. to select latents from groups, or models). 

It would therefore be nice to be able to store an Int Number under the respective switches in the bypass, which can be used via a second output to control other switches. The number should only be active when toggling.

**Comment by rgthree** [comment]
This seems like an anti pattern to rgthree-comfy. I assume when you say "switches" you mean the int-based from other node suites and not the rgthree-comfy switches?

I ask because rgthree-comfy nodes and switches power-up muting as a mechanism to skip workflow parts by taking the first non-null/muted input as aopposed to manually setting an int on a switch. To do so, you would use Group Muters, with Context nodes and Context Switches to bypass groups you don't want to execute and ensuring they don't run.

Simplest example would be the following, which is essentially similar to bypassing that node, but without any surprises, especially if a node has different inputs/ouputs:
![Screenshot 2024-07-16 210701](https://github.com/user-attachments/assets/54582918-153d-4031-8b75-c2756584bf0e)

But a more interesting example would be something like this:

![Screenshot 2024-07-16 210743](https://github.com/user-attachments/assets/6274ee0d-ae4b-43b2-bb29-b95594c197d6)

In both of these, when the group is muted, all the data going towards the resulting Context node or Context Switch is None and it's falling back to the next/base Context.

(You can also do the same using the Any Switch from rgthree-comfy, which works the same way, but without Context nodes. No INTs required, it just takes the first non-muted/null input).

Obviously, the Group Muter/Bypasser without using Context nodes and Switches, but that's only half the power. But if you really wanted to, then I would just put a primitive INT node in the groups being muted or not and that would just be passed to the switch.
