### ISSUE TITLE
USE CASE question: how to use bypass with a "conditional" workflow

### ISSUE THREAD

**Issue by tusharbhutt** [rgthree/rgthree-comfy#31]
Hi,

I have a node that picks a prompt process based random integer. Given an input, the workflow runs one of the nodes that corresponds to the integer picked.  However,r in the console, I see the non-selected nodes are still doing their prompting.  Is it possible to use the mute/bypass nodes to turn them off?  The workflow is shown below:

![image](https://github.com/rgthree/rgthree-comfy/assets/26264462/ac5997fd-0ac8-4d6e-b691-c134f43f296b)

So really what I want to do is if Wildcards is picked, to bypass/mute the other three, for example.

**Comment by rgthree** [comment]
Yea, that's the problem with other switch nodes; they don't stop the work from being done... muting is the way here.

But, your exact workflow wasn't supported.. until now :)

I've added a "Random Unmuter" and an "Any Switch" which means you can now mute all nodes going into a rgthree Context/Any Switch, and the "Random Unmuter" will unmute one input randomly. (This is similar to a Fast Muter, but done randomly at queue time, rather than a toggle by the user)

Here's an example workflow:
![workflow(6)](https://github.com/rgthree/rgthree-comfy/assets/476360/42462777-5dcd-4e4f-8691-4d4220522688)

**Comment by tusharbhutt** [comment]
WOO-HOO!  Will have to try it out :)

**Comment by tusharbhutt** [comment]
WOO-HOO!  I'll have to give it a try!
