### ISSUE TITLE
Suggestion: Custom Pipe Node

### ISSUE THREAD

**Issue by Trobinou** [rgthree/rgthree-comfy#36]
The 'pipe' nodes already exist, but they are predefined. I rarely use them because they don't allow me to transmit all the data I want.

The idea would be to connect any node to the 'custom pipe' node in order to truly have a workflow with as few lines as possible.

![custom pipe](https://github.com/rgthree/rgthree-comfy/assets/132901709/e123eaec-5f20-449b-87b2-f92bfbde6e9d)

Do you think such a node makes sense, and does it appeal to you?

**Comment by rgthree** [comment]
So that's exactly what I've made `Context` (and, `Context - Big`) for. It's essentially a more robust "Pipe" from other nodes, but much more flexible since the node itself can merge in new data, and output data from a single note (without needing "from pipe" nodes, etc).

![context_open](https://github.com/rgthree/rgthree-comfy/assets/476360/2c179bf5-1f85-4cf9-b181-9e8cabdf1df6)

So, they can be used to transmit large contextual data across a workflow, but also merge in. Of course, the cleanliness comes from collapsing them:

![context_closed](https://github.com/rgthree/rgthree-comfy/assets/476360/2d16155e-38dd-4a07-9896-518de308dba8)

**Comment by Trobinou** [comment]
Oh 😮 I'm sorry I didn't see the point of this node sooner, I blame myself 😄
Thanks for your reply, next time I'll be more vigilant before asking a question!
