### ISSUE TITLE
Group bypass button no longer work

### ISSUE THREAD

**Issue by dchatel** [rgthree/rgthree-comfy#361]
In ComfyUI v0.2.7-2-g69694f4, ComfyUI_frontend v1.3.32, the button at the top right corner of groups no longer work if any node contained in the group overlaps with another node in another group.

And upon further inspection, the repeater doesn't work anymore, again.

**Comment by rgthree** [comment]
@dchatel Do the buttons not work at all, or just that node that extends into another group not working? (The buttons still work fine for me, but the node that extends into another group no longer toggles). See the screenshot below, for my repro, the buttons still work, but that `Preview Image` node no longer toggles. Can you confirm that's the behavior you see?

For the issue I see (a node extending off the group) seems to be related to this commit: https://github.com/Comfy-Org/litegraph.js/commit/1b110a62cf91e3f89f8940d3837ff1514641cb45#r148771647 

@webfiltered Looks like that changes what LiteGraph considers to be a node "inside a group" to now requiring it's center point to be within the group. In my repro case, simply having a node that starts well within a group, but may extend off it such that its center point is outside the group bounds, no longer is considered "inside a group" whereas it used to.

See this:
![Screenshot 2024-11-05 214905](https://github.com/user-attachments/assets/49c0d212-3efa-4e7a-b097-d8a2043ab3dd)

That `Preview Image` node is now not considered "inside the group" because that commit changes it to be the center point where, I believe, most users would expect that to be considered "inside the group."

**Comment by rgthree** [comment]
> And upon further inspection, the repeater doesn't work anymore, again.

@dchatel Do you use the latest use everywhere extension? It stops repeater and relay and other nodes from working correctly, see: https://github.com/chrisgoringe/cg-use-everywhere/issues/244

**Comment by chrisgoringe** [comment]
use everywhere updated to 5.0.6 which should fix this problem - thanks @rgthree for the heads up and the code!

**Comment by dchatel** [comment]
I updated cg_use_everywhere to 5.0.6 and indeed it works now, except for that borderline case where the node center is not inside the group.
Good job!

**Comment by JorgeR81** [comment]
> (and you will be able to drag a group across an area without unintentionally collecting half a dozen nodes along the way).

@webfiltered, does this happen to you ?

This happened to me a while back. When I dragged a group across other nodes it would collect them.

But this is not normal ComfyUI behaviour. It was a bug caused by ComfyUI extensions.

I only got rid of that, when it was fixed, both in `cg_use_everywhere` and `rgthree-comfy` ( https://github.com/rgthree/rgthree-comfy/issues/181 )

So maybe you have another extension that causes this issue for you ?
