### ISSUE TITLE
Bookmarks intermittently stop working until a restart.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [rgthree/rgthree-comfy#376]
This has happened over the past couple of days, but I've been using the bookmarks for several hours without any problem. They suddenly stop working, with no errors or obvious reason. I've tried different workflows, reloading the same one, but the only way I can get them working again is to stop/start ComfyUI. The problem seemed to start around the same time as the lora loader add button stopped working, so may be related in some way.

After typing this, I went back to my ComfyUI tab, and they started working again, without a restart!

**Comment by LukeG89** [comment]
I think I've had this problem for about a month now, but it has occurred only a few times during this period. I've never been able to figure out the cause. It could be another conflict with the frontend, in this case the keybindings system. But I think it's hard to solve the problem if we can't reproduce it.

**Comment by rgthree** [comment]
> After typing this, I went back to my ComfyUI tab, and they started working again, without a restart!

Sometimes a key gets stuck as "pressed" in the code do to something else taking control. To help combat this, I reset all keys to "not currently pressed" when the tab loses and regains focus (as in, "going back to your comfy tab").

Two questions:
1) What OS and browser are you on?
2) Can you think of what keyboard actions you would last take that would then cause the bookmarks to stop working? This is _usually_ something that removes control from the window, like a browser or OS key shortcut), but it could be something new in ComfyUI or an extension that is not bubbling an event so rgthree-comfy knows the status).

---
Explanation: In the browser JavaScript, you can't actually know if a key is "currently pressed" only that it _has been pressed_ and _has been released_ so to track the current state of a key, we need listen to both the _pressed_ and _released_ and consider a key "currently pressed" in between these two states. Unfortunately, in some situations it's not impossible to miss a _released_ resulting in the key continuing to look pressed. Bookmarks work by key combination. So if "ctrl" is "stuck" as pressed even when it's not, and you press "1" the bookmark may not work because it thinks you're pressing "ctrl + 1".

**Comment by LukeG89** [comment]
About your questions:

1. I'm on Windows using Chrome
2. I can't remember since it happened just a few times

> Sometimes a key gets stuck as "pressed" in the code

I think this is the problem, I don't think it's due to a conflict with frontend or other extensions. 

> So if "ctrl" is "stuck" as pressed even when it's not, and you press "1" the bookmark may not work because it thinks you're pressing "ctrl + 1".

One time I had a problem while trying to change the key in a bookmark: When I pressed the new key, another key + the new key were entered. Now I understand why! Thanks for the explanation!

**Comment by GalaxyTimeMachine** [comment]
I was using Windows 11 and Edge browser.

**Comment by rgthree** [comment]
Hmmm. Wasn't expecting Windows and chrome. To help, I've just added a debug option to show what keys rgthree-comfy thinks is currently down.

If you pull the latest, and add the following to you `rgthree_config.json` in the rgthree-comfy directory it will put a small label in the top-right of your window showing those current keys.

```json
  "debug": {
    "keys_down": {
      "enabled": true
    }
  }
```

If you notice bookmarks not working again, check up there and see if some keys are "stuck." If not, something else may be going on and this was just a red herring.

**Comment by idesign2018** [comment]
> Hmmm. Wasn't expecting Windows and chrome. To help, I've just added a debug option to show what keys rgthree-comfy thinks is currently down.
> 
> If you pull the latest, and add the following to you `rgthree_config.json` in the rgthree-comfy directory it will put a small label in the top-right of your window showing those current keys.
> 
> ```json
>   "debug": {
>     "keys_down": {
>       "enabled": true
>     }
>   }
> ```
> 
> If you notice bookmarks not working again, check up there and see if some keys are "stuck." If not, something else may be going on and this was just a red herring.

I added this code to the `rgthree_config.json` file in the `rgthree-comfy` directory, but it still doesn't work
```python
{
  "features": {
    "group_header_fast_toggle": {
      "enabled": true
    },
    "import_individual_nodes": {
      "enabled": true
    },
    "menu_auto_nest": {
      "subdirs": true
    },
    "progress_bar": {
      "height": 16
    },
    "show_alerts_for_corrupt_workflows": true
  },
  
  "debug": {
    "keys_down": {
      "enabled": true
    }
  }
}
```

**Comment by idesign2018** [comment]
When my ComfyUI is in Chinese, the label does not work properly, as shown below:
![image](https://github.com/user-attachments/assets/808fee6b-533a-496b-b687-e0c054d76b1c)

When my ComfyUI is in English, the label works fine, as shown below:
![image](https://github.com/user-attachments/assets/4f8d2125-8d31-4318-87c4-ab1963317d2d)

This problem seems to have appeared a long time ago.
I am currently using the ComfyUI desktop version.

If I try to switch from the English interface to the Chinese interface, the labels don't work properly.

**Comment by idesign2018** [comment]
我在[AIGODLIKE-ComfyUI-Translation](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation)提交了bug问题

https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/308

**Comment by brucew4yn3rp** [comment]
@rgthree Confirming that the issue is because of ComfyUI not registering the depress of "_" 

If a user presses Shift + "-" to type an underscore, but releases the Shift key first, the program believes the underscore key to be continually pressed.

**Proposed Solution in bookmark.js below. Just adding an extendedShortcut variable**
```
    onKeypress(event) {
        const originalEvent = event.detail.originalEvent;
        const target = originalEvent.target;
    
        if (getClosestOrSelf(target, 'input,textarea,[contenteditable="true"]')) {
            return;
        }
    
        const shortcutKey = this.shortcutKey;
        const pressedKey = originalEvent.key.toLocaleLowerCase();
        const baseShortcut = this.widgets[0].value;
        const extendedShortcut = `${baseShortcut}_`; // Shortcut with "_"
    
        if (
            KEY_EVENT_SERVICE.areOnlyKeysDown(baseShortcut, true) ||
            KEY_EVENT_SERVICE.areOnlyKeysDown(extendedShortcut, true)
        ) {
            this.canvasToBookmark();
            originalEvent.preventDefault();
            originalEvent.stopPropagation();
        }
    }
```

**Comment by rgthree** [comment]
> If a user presses Shift + "-" to type an underscore, but releases the Shift key first, the program believes the underscore key to be continually pressed.

Thank you! Looks like it happens with any key for that SHIFT behavior. Latest push should fix it, but "releasing" all keys pressed while SHIFT was pressed when SHIFT is released. Looks like keys that are still pressed (or their alt, like "-" instead of "_") will fire a new "keydown" to be captured again.
