### ISSUE TITLE
'Fast Groups Muter' node doesn't appear in ComfyUI's /object_info

### ISSUE THREAD

**Issue by chezolver** [rgthree/rgthree-comfy#378]
Hello,

The 'Fast Groups Muter' node doesn't appear in ComfyUI's /object_info , so ComfyUIMini or other apps that rely on the ComfyUI API, won't be able to see it.

https://github.com/ImDarkTom/ComfyUIMini/issues/19#issuecomment-2491583767

**Comment by rgthree** [comment]
Many nodes, including the Fast Groups Muter are client-only nodes (aka "Virtual Node" in comfy). There's no object_info because the server doesn't know anything about the node. On the client, the node mutes/unmutes groups when clicked, but isn't sent to the server since there's no work that needs to be done, the groups are already in their correct state.
