### ISSUE TITLE
LoRA Power Loader: Unable to set strength manually

### ISSUE THREAD

**Issue by gonzalu** [rgthree/rgthree-comfy#388]
After a recent update, I can no longer click on the strength itself to open the pop-up where I can enter the strength manually. 

I am still able to use the left and right arrows next to the number but those only increment in values of .05 not less. 

Thank you.

**Comment by gonzalu** [comment]
These are the last few lines of the DevTools Console Output

![image](https://github.com/user-attachments/assets/8bcecc96-17c1-4b61-9cea-9942e2ae0430)

**Comment by novice-101** [comment]
Same issue

**Comment by APCOTech** [comment]
Hi, yesterday, I posted the same issue and @rgthree explained it so my issue is closed now, here is the answer:
> ComfyOrg accidentally broke this and they've fixed it in `ComfyUI_frontend v1.5.0`. See this comment [#375 (comment)](https://github.com/rgthree/rgthree-comfy/issues/375#issuecomment-2507584179) in the duplicate, larger issue. Thx

In short, it is a comfyUI problem. It is fixed in the FrontEnd 1.5 which is not published so far. So you have two options:
1) Wait for the next week and it will be fixed automatically for you.
2) Edit (run_nvidia_gpu.bat and aAdd this argument (--front-end-version Comfy-Org/ComfyUI_frontend@latest) at the end to force ComfyUI to run on the latest frontend.
Good luck.

**Comment by gonzalu** [comment]
> Hi, yesterday, I posted the same issue and @rgthree explained it so my issue is closed now, here is the answer:
> 
> > ComfyOrg accidentally broke this and they've fixed it in `ComfyUI_frontend v1.5.0`. See this comment [#375 (comment)](https://github.com/rgthree/rgthree-comfy/issues/375#issuecomment-2507584179) in the duplicate, larger issue. Thx
> 
> In short, it is a comfyUI problem. It is fixed in the FrontEnd 1.5 which is not published so far. So you have two options:
> 
> 1. Wait for the next week and it will be fixed automatically for you.
> 2. Edit (run_nvidia_gpu.bat and aAdd this argument (--front-end-version Comfy-Org/ComfyUI_frontend@latest) at the end to force ComfyUI to run on the latest frontend.
>    Good luck.

You're awesome. Thank you. I searched before posting but did not see your post :( My bad for duplicating. 

I will wait for natural update to fix it :D  

Thank you and cheers!

**Comment by gonzalu** [comment]
Looks like after latest update, the problem was not fixed by the UI team :( 

I don't like mucking around with my command line options so I guess I'll wait for either rgthree to fix the nodes or for ComfyUI frontend to help... 

Here is the version I am on... 

![image](https://github.com/user-attachments/assets/8d2631fb-2512-4778-8ac6-68de647aa876)


> Hi, yesterday, I posted the same issue and @rgthree explained it so my issue is closed now, here is the answer:
> 
> > ComfyOrg accidentally broke this and they've fixed it in `ComfyUI_frontend v1.5.0`. See this comment [#375 (comment)](https://github.com/rgthree/rgthree-comfy/issues/375#issuecomment-2507584179) in the duplicate, larger issue. Thx
> 
> In short, it is a comfyUI problem. It is fixed in the FrontEnd 1.5 which is not published so far. So you have two options:
> 
> 1. Wait for the next week and it will be fixed automatically for you.
> 2. Edit (run_nvidia_gpu.bat and aAdd this argument (--front-end-version Comfy-Org/ComfyUI_frontend@latest) at the end to force ComfyUI to run on the latest frontend.
>    Good luck.

**Comment by gonzalu** [comment]
@rgthree any way you could allow single integer precision instead of 5 jump until we can enter the number directly again? At least when I slide it around, I can get close and then get to the exact number I need one click of the arrows at a time. 

Thank you.

**Comment by rgthree** [comment]
Hey all, ComfyOrg accidentally broke this and they've fixed it in ComfyUI_frontend v1.5.0.

It look like that's the next version is v1.5.0 so you should be OK after that. Until then, you can always designate which frontend version you want to use when you start up comfy. For instance, add ` --front-end-version Comfy-Org/ComfyUI_frontend@latest` to your command startup to use the latest front end version, or `v1.5.0` to use the next.

Yuo can see more info in this duplicate thread https://github.com/rgthree/rgthree-comfy/issues/375#issuecomment-2507584179 Thx

> any way you could allow single integer precision instead of 5 jump until we can enter the number directly again? At least when I slide it around, I can get close and then get to the exact number I need one click of the arrows at a time.

@gonzalu I actually like this suggestion, but since it's trivial to designate the fixed version in the startup command AND the next version from the ComfyUI's current version, I'm not planning to make a change here (at least not faster than I assume ComfyUI should push the next version)

**Comment by gonzalu** [comment]
No worries and thank you regardless :D 

Cheers!
