### ISSUE TITLE
Saved Prompts Feature of Power Prompt Fails to Load Files

### ISSUE THREAD

**Issue by kkriehl** [rgthree/rgthree-comfy#398]
The `saved_prompts` directory and included files can't be found during the node initialization. This is because the directory added to `folder_names_and_paths` [during the pre-startup script](https://github.com/rgthree/rgthree-comfy/blob/main/prestartup_script.py#L4) has no full path on the file system and ComfyUI [iterates over the empty list](https://github.com/comfyanonymous/ComfyUI/blob/master/folder_paths.py#L297) to fill the cache that is used by `get_filename_list` in [power_prompt.py](https://github.com/rgthree/rgthree-comfy/blob/main/py/power_prompt.py#L20).

Adding the full path to the directory fixes this:
```python
import os
import folder_paths

# Add 'saved_prompts' as a folder for Power Prompt node.
folder_paths.folder_names_and_paths['saved_prompts'] = ([os.path.join(folder_paths.base_path, 'saved_prompts')], set(['.txt']))
```

(I didn't create a PR for this since I don't know where the `saved_prompts` directory is intended to be. Although the empty list makes me _assume_ that it would be the ComfyUI root.)

**Comment by rgthree** [comment]
Interesting. It definitely worked when I first added it; I wonder what broke.

Your code change does fix it, but ties it only to the base_path, whereas the original folder_names_and_path would use the `base` of the extra_paths yaml file if defined. Not sure if that's why I had an empty list there and it worked accidentally at the time.

Anyway, clearly no one is using this as I'm not sure it's been working for a while, it does cause issues for some installs (#399 for instance), and it's not how I would go about it now.

I've removed it for now and if enough ppl tell me they actually used it, maybe I'll rethink the idea.
