### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by johnathan2738** [rgthree/rgthree-comfy#59]
![Uploading 截圖 2023-11-27 晚上9.51.11.jp
![截圖 2023-11-27 晚上9 51 18](https://github.com/rgthree/rgthree-comfy/assets/22163731/dbd7e90f-de76-4ffd-86f8-1ed6ada2e502)
g…]()

**Comment by johnathan2738** [comment]
![截圖 2023-11-27 晚上9 51 11](https://github.com/rgthree/rgthree-comfy/assets/22163731/75df429d-f342-412e-928e-7afa96e3629c)

**Comment by rgthree** [comment]
Do you see an error in the terminal? I can't tell what's wrong from just these screenshots. Could be a bug in the manager.

**Comment by johnathan2738** [comment]
I found the problem, because I use python 3.9

**Comment by heizaheiza** [comment]
Your ComfyUI application encountered a problem during startup, preventing the successful import of the rgthree-comfy custom node module. This issue is due to incorrect usage of the glob.glob function in the __init__.py file. Specifically, the glob.glob function was incorrectly passed a keyword argument named root_dir, which is actually not part of the glob.glob function.

To resolve this issue, you need to modify the code in the rgthree-comfy module:

1.Open the __init__.py File:

Locate the file at E:\new_ComfyUI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\__init__.py.
 
2.Modify the Problematic Line of Code:

Find the line of code causing the error (line 98).
Change the glob.glob call in this line to the correct format. You need to combine the directory path directly with the wildcard, instead of using the root_dir parameter.

3.Correct glob.glob Call Example:

The original code might look something like this:

 **for file in glob.glob('*.py', root_dir=DIR_PY) + glob.glob('*.js', root_dir=os.path.join(DIR_DEV_WEB, 'js')):**

It should be modified to something like the following format:

 **for file in glob.glob(os.path.join(DIR_PY, '*.py')) + glob.glob(os.path.join(DIR_DEV_WEB, 'js', '*.js')):**

4.Save the File and Restart ComfyUI:

Save the changes made to the __init__.py file.
Restart the ComfyUI application for the changes to take effect.
