### ISSUE TITLE
Un- / lock missing 

### ISSUE THREAD

**Issue by OmegaII** [rgthree/rgthree-comfy#60]
I see that Lock / Unlock is missing. I can lock and unlock when selecting multiple nodes, where I can do the action on the other node. 
But the option is missing on any of your nodes. 
![image](https://github.com/rgthree/rgthree-comfy/assets/18040590/dd90ba35-f9ae-4c0f-b471-bfe80e62b211)

**Comment by rgthree** [comment]
Looks like locking comes from another extension and is not part of native ComfyUI. Specifically, github.com/pythongosssss/ComfyUI-Custom-Script

Because of the way my nodes are working, and they are adding these menu items, they're not compatible. I'm able to fix it on my end for Seed, and the Context nodes, but for other nodes (like Fast Muter, etc.) there's no other way than for it to be fixed from pythongosssss/ComfyUI-Custom-Script side, because these other nodes are "virtual nodes" and @pythongosssss is only overriding server nodes.

I see the ttN extension is adding menu items to my virtual nodes, so it's likely possible to fix on their side.
