### ISSUE TITLE
rgthree seed is jumping out of random to last used number

### ISSUE THREAD

**Issue by f-rank** [rgthree/rgthree-comfy#62]
Whenever a bypass is activated on a node or whenever a node in the comp is repositioned.
Probably a weird interaction with something else, maybe.
Either way if anyone is experiencing this, would be good to compare installed nodes list.

**Comment by rgthree** [comment]
I can't seem to reproduce this... do you have a workflow example it's happening for? The seed shouldn't change on its own. It is possible that another custom node suite is messing around.

One thing worth mentioning is that the node actually saves the seed to the workflow and in the image metadata, and then switches it back to "-1". This is by design so you can pull in a generated image and it will be the correct seed already set (instead of "-1 randomize"). I wonder if your workflow is reloading in the window somehow.. maybe even by another node.

**Comment by f-rank** [comment]
I think it must be something local at this point, given your confirmation that you can't reproduce.
Weird that it worked perfect for so long and now it is borking this way.
It is really annoying because you have to go set it again each time.
Here is a workflow that reproduces the seed jump.
https://pastebin.com/BeqaF3Nz
You set it to random. The first goes through, moment you click on any other node, the seed keeps sticking on the next generations.

> I can't seem to reproduce this... do you have a workflow example it's happening for? The seed shouldn't change on its own. It is possible that another custom node suite is messing around.
> 
> One thing worth mentioning is that the node actually saves the seed to the workflow and in the image metadata, and then switches it back to "-1". This is by design so you can pull in a generated image and it will be the correct seed already set (instead of "-1 randomize"). I wonder if your workflow is reloading in the window somehow.. maybe even by another node.

**Comment by noembryo** [comment]
Same thing happens here too.
@f-rank Checked your json too. The same as with mine.
You don't need to run any prompt.
Just click on any node after setting the seed to random, and its back on the last one.
If after that you click again, the "Use last queued seed" is cleared too.

**Comment by noembryo** [comment]
Checking with a cleared workflow that contains only the seed node.
Deselecting and re-selecting the node reproduces the problem.. 🤔

**Comment by rgthree** [comment]
Hmm.. @f-rank I tried your JSON workflow and it is also working fine for me. I'm not sure what's going on.

What custom nodes do you have installed? I wonder if there's a conflict with seeds, or global seeds, or something like that in another node quite..

**Comment by rgthree** [comment]
Ok, I think it is the cg-use-everywhere custom nodes. I just installed them, and now my seed node won't stay on -1 either...

To verify, could @f-rank or @noembryo try removing that custom node and seeing if it does work. I'll see if I can understand why it's conflicting.

**Comment by rgthree** [comment]
Okay, this should be fixed now. The problem was that cg-use-everywhere serializes the graph to analyze the links often (which is why it was happening even by clicking on a node) but the rgthree Seed node swaps the value on serialization but never gets the signal to swap back since the queue isn't running.

The fix only does the swap when we know the queue is being processed, rather than everytime the widget is serialized.

**Comment by noembryo** [comment]
Updated and fixed! 🚀 
Thanks @rgthree

**Comment by f-rank** [comment]
... ok, so now if I try to add it to a new workflow, nothing happens when I queue prompt @rgthree
Working great on workflows where it already existed. Adding it to a new one stops the worflow from entering queue it seems.

**Comment by noembryo** [comment]
@f-rank If you clear your workflow and add seed and "Display int" node, what happens?
I did it here and it works as expected..

**Comment by f-rank** [comment]
Actually that, and a lot of hitting queue workflow, made it work. Thanks @noembryo.
I hope general weirdness is now somehow fixed.

> @f-rank If you clear your workflow and add seed and "Display int" node, what happens? I did it here and it works as expected..
