### ISSUE TITLE
Question: On fast mute/bypass convert "enable" to input?

### ISSUE THREAD

**Issue by CHollman82** [rgthree/rgthree-comfy#70]
Hi, I was wondering if there is a reason we can't convert the enable widget on the fast mute or bypass nodes to a node input? I was considering trying to roll my own node based on your code but if there is some inherent limitation that prevents this it would save me some time trying to do something impossible, thanks.

What I want to do is randomly enable or disable different groups, specifically I want to randomly enable 1 of n groups and disable all of the others...

**Comment by rgthree** [comment]
Hi! So, that won't work with this nodes' widgets. Since it's a VirtualNode, there's nothing to input; it's behavior is all in the UI and coded by interaction, not driven by inputs and sent to the backend.

But.. you can do what you'd like with my current nodes though. There's a "Random Unmuter" node, combine that with "Mute/Bypass Repeater Nodes" on groups, start them as muted, and when a prompt is queued the "Random Unmuter" will unmute one, then mute it back (it may happen so fast, it looks like nothing was unmuted, but it will work, and should be saved to the outputs metadata as unmuted).

Here's an example using seed, any switch, and display any. You'll notice each time you run this, the display any node will change, randomly, to 1, 2, or 3 (meaning one of the groups were unmuted with those seeds):
![workflow_random_groups](https://github.com/rgthree/rgthree-comfy/assets/476360/fe203b28-6211-4b5c-9de4-642049992201)

**Comment by CHollman82** [comment]
Thank you so much for taking the time to make that example, that's very helpful!
