### ISSUE TITLE
Is there a way to control the landing coordinates of Fast Groups Muter/Bypasser node's hyperjump?

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#72]
This new hyperjump feature could be exceptionally useful, replacing the need for graphNavigator, except that it's really hard it never centers the group in the viewport. At least on my system, what happens is that the top-left corner of the group ends up almost at the bottom-right corner of the screen, making the group practically invisible and, probably, very confusing for somebody that is not familiar with the workflow being displayed.

Not sure it's possible, but I'd hope that these hyperjump buttons would change the zoom level so that the group fits the whole viewport and center that group on the screen. 

--
A very, very, minor side node: the color of the hyperjump arrow is the same of the toggle. So, when the workflow is reasonably zoomed out, and I look at the control panel I created, it sees like I toggled on a lot of features I didn't intend to. So I have to go and double-check again with a zoom in.

**Comment by rgthree** [comment]
Hmm.. the hyperjump is using the framework's built-in `centerOnNode()` method, which seems to work for me. I can't seem to reproduce it ever _not_ moving so the center of the group, is centered in the viewport (tried really zoomed in, zoomed out, etc).

Question, if you right click and select "Follow Execution" (which another common extension provides; I forget which one but you prob have it) and start an execution, does it follow along with the current node in the center? That uses the same method, I believe... curious to see if it's also not working for you.

For the side note; good point. 14e78bb makes it so that the custom widget row renders itself like other widgets when zoomed out (no text, no nav arrow, just the toggle color). So, that should be good now.

**Comment by alessandroperilli** [comment]
This explains everything: the Follow Execution feature never worked for me because it does exactly the same weirdness it does with your hyperjump. I didn't realize the connection until you mentioned it. 

I use Vivaldi on macOS and that's probably the reason for some sort of obscure incompatibility. And given that I won't be able to change the browser for this one thing, I guess I'll just live with it and close the issue.

P.s.: the zoom out view looks way less disorienting now. Thank you.
