### ISSUE TITLE
[Feature] Add more connection layouts to Context

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#94]
I seem to often have multiple different things (like positive, negative) that follow a similar path, and need similar "rerouting". I could use the context node to do that, however, it doesn't currently support all the different connection layouts as a "reroute" node does.

**Comment by rgthree** [comment]
Unfortunately, Reroute nodes can be be uniquely special because they only have only one input and output, making it much more flexible than other nodes that would run into many issues with more than one.

To achieve the reroute flexibility, I'd recommend either bringin multiple into a Context node, and using the single CONTEXT output to reroute nodes to move around your workflow, then ending into another Context node to provide the multiple outputs. Or, just us multiple reroute nodes, especially if it's only two connections.

**Comment by ghostsquad** [comment]
Excellent idea. Thank you!
